### ISSUE TITLE
Notification at the top indicating whether MobiPerf is running in the background

### ISSUE THREAD

**Issue by quietbamboo** [Mobiperf/MobiPerf#12] opened 2012-03-30 04:46 UTC
Add notification at the top indicating whether MobiPerf is running in the background, i.e., whether periodic setting is enabled or not in the preference page

**Comment by mdwelsh** [comment] 2012-04-16 01:52
Can you clarify what you mean by "at the top"? This could mean within the activity window or on the Android status bar. Actually, either is good - I tend to prefer an icon in the status bar, which also helps the app to run more often (since Android gives apps with status bar icons priority); however, a lot of users complained about this when we did it with Speedometer, so I disabled it.

Anyway - I would like to see some kind of app status on the main page of the app including:
- Whether background measurements are active
- How long since last checkin
- Total number of measurements run since last checkin
- Whether measurement is currently disabled due to battery threshold or WiFi being on.

**Comment by huangshu91** [comment] 2012-05-28 09:39
Matt, how should the app status be displayed on the main page?  I'm confused on what this will look like and how to fit all this information on the main page.

**Comment by mdwelsh** [comment] 2012-05-28 21:25
How about this: At the top of the main window (above the 6 buttons) a little text box with enough room for a few lines (say 3 lines) of status text. We can then update that status from anywhere in the app to include things like "Background measurement disabled due to low battery", "Ping measurement running", etc. It just serves as a single place to see what the app's current status is.

**Comment by quietbamboo** [comment] 2012-06-08 16:59
Shuheng, can we close this issue now?

**Comment by mdwelsh** [comment] 2012-07-27 21:14
This is not done yet. Code: http://speedometer-reviews.appspot.com/6002/

**Comment by mdwelsh** [comment] 2012-08-31 18:35
Should make this a default in the beta release.

**Comment by ghost** [comment] 2012-09-04 20:46
The code review link is still not LGTM'd. Did it ever get finished?
I don't see anything in the code review that stops it being a default now.

**Comment by huangshu91** [comment] 2012-09-04 21:11
No, this was up for review but we decided to roll back before this was ever
finished.

// TODO(mdw): Make this a user-selectable option
    //startSpeedomterInForeGround();

I think running in the background is the default currently but,
ideally it is an option and there is an additional notification about
which is currently set.

**Comment by mdwelsh** [comment] 2012-09-04 22:10
Please keep the issue open but we need to make this change in the new
codebase.

**Comment by ghost** [comment] 2012-09-22 02:14
Here's what I'd really like to see, having played with the app a bit:

A small icon in the notification area when Mobiperf is running in the background. When the user expands the notification area, there should be a line item for Mobiperf with a status text. This item should not be 'swipable'.

WDYT?

**Comment by mdwelsh** [comment] 2012-09-22 15:12
We had this originally and there is code in Speedometer to do it - I think
you have to comment out a couple of lines to turn it on. The problem is
that a bunch of users complained about it. So we should decide...

**Comment by quietbamboo** [comment] 2012-09-22 16:00
Can we make the notification "swipable" so as to be more user-friendly?
At least, the user will know that MobiPerf is running in the background before they clear the notification field.

**Comment by ghost** [comment] 2012-09-24 15:29
What was the nature of the complaint? This is a fairly standard thing that other applications do. Making it swipable would be more confusing, i think, as it might lead the user to think they're closing the process, which they wouldn't be.

**Comment by mdwelsh** [comment] 2012-09-24 15:31
A bunch of people complained about it taking up space in the menu bar. It's
also not very aesthetic to have yet another icon there.

**Comment by ghost** [comment] 2012-09-24 15:49
I know many apps have background processes that don't show up as icons, but for Mobiperf it feels strange. Possibly because it's such an active process - ie, it's not just waiting for push notifications or polling a server, but is running tests that use CPU/RAM and therefore battery. It's also somewhere to alert the user to the status without cluttering up the main UI.

People will always complain about it taking up space, but not having it is worse, I think.

**Comment by quietbamboo** [comment] 2012-09-24 15:52
A compromise might be, if not making things worse, add in the settings an option for users to disable/enable such notifications, and whether to set the default to on or off is to be discussed.

**Comment by ghost** [comment] 2012-09-24 15:57
Sounds fair, as long as it doesn't delay launch further. In the interests of launching sooner we could add the icon and then work on a preference to disable it ;)

**Comment by ghost** [comment] 2012-09-24 18:49
http://speedometer-reviews.appspot.com/28001/

**Closed as completed** 2012-09-24 18:55 UTC
